#pragma once
#include <string>
// This file is generated by CLKernelPreprocessor, any changes made in this file will be lost

const std::string VectorComplexDivision0 = R"(//
// MIT license
//
// Copyright (c) 2019 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

#include <metal_stdlib>
using namespace metal;

kernel void VectorComplexDiv(
    device const float* inA,
    device float* result,
    uint index [[thread_position_in_grid]])
{
    result[index] = -inA[index] * inA[index] * inA[index];
})";
const std::string VectorComplexDivision_Str = VectorComplexDivision0;
static const char* VectorComplexDivision = &VectorComplexDivision_Str[0u];
const size_t VectorComplexDivisionCount = VectorComplexDivision_Str.size();
